name: powershell
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'
      - 'releases/**'
      - 'feature/**'
  # workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
#       - name: Run a one-line script
#         run: echo Hello, world!
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
      - name: Install webi
        shell: pwsh
          # Set-ExecutionPolicy -Scope {Process | CurrentUser | LocalMachine | UserPolicy | MachinePolicy} Restricted | Bypass
        run: |
          cd $Env:USERPROFILE
          Set-ExecutionPolicy -Scope CurrentUser Bypass
          curl.exe -A "MS" https://webinstall.dev/webi | pwsh
          Set-Content -Path env:PATH -Value ('C:\Users\runneradmin/.local/bin;' + $env:PATH)
          echo $Env:USERPROFILE
          cd $Env:USERPROFILE\.local\bin
          dir
      - name: Show webi help
        shell: pwsh
        run: .\.local\bin\webi-pwsh.ps1 --help
      # - name: Perform a Webi Install Test
      #   shell: pwsh
      #   run: |
      #     Invoke-Pester test/install.ps1 -Passthru